### ISSUE TITLE
存档模块

### ISSUE THREAD

**Issue by umiringo** [umiringo/Wonambi#174]
存档mgr
提供功能：
1，多份存档支持
2，存档数据类的序列化和写文件
3，反序列化和读取生存
4，删除，新增
5，存档数据类本体（尽可能支持复杂数据结构)

**Comment by xuzhaocheng** [comment]
ArchiveMgr <singleton>
	+ maxSize
	- archiveBrifList


	- refresh()
	- loadArchive(int idx)
	- deleteArchive(int idx)
	- save(int idx, GameData Data)

GameData
	+ inst
	+ set(GameData data)

AchiveBrif
	- dataPath
	- date
	- data need display on archive menu


Directory Hierachy
	- Achives
		- Brif1
		- Brif2
		- Brif3
		...
		- data
			- data1
			- data2
			...

**Comment by umiringo** [comment]
函数首字母大写

**Comment by xuzhaocheng** [comment]
存档加密
超出maxSize不允许新建

**Comment by umiringo** [comment]
@xuzhaocheng 
存档模块，我看了下，基本上可以的。
但是要考虑到不同类的存档，不知道你那个AchiveRef类是否可以作为基类继承，如果继承，需要实现的函数做虚吧
还有要考虑到一个全局存档的问题（游戏配置，上次使用的存档，现有的存档），我觉得全部归到全局存档里面比较好
这个指针理论上是放在gameMgr里面，但是初始化的时候我又想是否应该放在AchiveMgr的初始化里面
你觉得呢

**Comment by xuzhaocheng** [comment]
@umiringo 
为什么会出现不同类的存档？有具体场景吗？继承的话就麻烦了，读的时候不知道是哪种类型的brif。但是可以分文件夹。
全局存档我能理解，这个好弄，把存档名字记在PlayerPref里，然后读出来就是了。
指针放在gameMgr里吧，AchiveMgr负责读出来。

**Comment by umiringo** [comment]
比如说全局的存档包含了所有存档的列表，按键设置，音量设置，这个打开游戏的一瞬间就要读到，不跟随具体某一个关卡存档走对吧，这不就是2种了？

**Comment by xuzhaocheng** [comment]
@umiringo 
哦这种是不需要brif的，直接定义一个新的类就可以了。AchiveBrif只是用来显示存档列表的信息的。

**Comment by umiringo** [comment]
@xuzhaocheng 所以具体的存盘内容还需要一个新类？明天见面再问你吧，我有点绕
