### ISSUE TITLE
使用新的碰撞，移动库来替代现有物理部分（player部分）

### ISSUE THREAD

**Issue by umiringo** [umiringo/Wonambi#175]
tile地形和player之间的处理
tile的component自动添加（chenyan）
player的操作，移动，跳跃，落下等处理

**Comment by umiringo** [comment]
@IpursueI player类需要满足的功能
1，跳跃上升的加速度是下落时候的一半
2，下落时要播下落动画
3，移动反应加快
4，在评论处写上二段跳调用的地方，我后面要加东西
5，最好加个文档，描述下要修改禁止爬墙，调整速度等参数的方法

**Comment by umiringo** [comment]
@IpursueI 
我又看了一下，你这个就不要做配置文件来修改配置了
直接hardcore
然后能否doublejump，设置doublejump
获取速度，设置速度
获取跳跃高度，设置跳跃高度这些配置都添加Get和Set接口

这个类比较重要也比较麻烦，多费心了

**Comment by IpursueI** [comment]
@umiringo 好，明天晚上我把这些调整一下

**Comment by IpursueI** [comment]
@umiringo platformerMotor2D 里面有public Action onAirJump;  二段跳的时候会触发，你把自己的函数赋值给它就好。

- [ ] 跳跃上升的加速度是下落时候的一半

- [ ] 下落时要播下落动画

- [ ] 移动反应加快

**Comment by IpursueI** [comment]
@umiringo 后面的文档，我明天再搞，这个是要单独写个类似readme的出来吗

**Comment by umiringo** [comment]
速度修改
跳跃高度修改
能否二段跳
跳跃的加速度
贴墙取消
**dash卡墙bug**
忽视重力

1，动态set，get
2，手动能改（在prefab修改值）

**Comment by IpursueI** [comment]
引擎接口文档目录 Wonambi\Assets\Docs\CustomPhysics.md
卡墙调参解决

**Comment by umiringo** [comment]
@IpursueI  Docs不能放在Asset下，你放在最外面，和psd同级别

**Comment by umiringo** [comment]
@IpursueI  我综合了ani和con，功能修正了下应该没什么大问题了，就是手感不太好，明天见面调整吧

**Comment by umiringo** [comment]
@IpursueI  今晚我们过一下参数，差不多这个单子可以结束了
