### ISSUE TITLE
rush怪

### ISSUE THREAD

**Issue by umiringo** [umiringo/Wonambi#199]
1，启动时快速向玩家方向移动
2，遇到坑掉落（如果掉到一定范围以下死亡）
3，遇到墙壁回头

- [x] 图

- [x] 动画

- [x] prefab

- [x] 逻辑

**Comment by umiringo** [comment]
- [x] 图

- [ ] 动画

- [ ] prefab

- [ ] 逻辑

**Comment by IpursueI** [comment]
每个怪物需要设置不同的行动范围
