### ISSUE TITLE
玩家调优

### ISSUE THREAD

**Issue by umiringo** [umiringo/Wonambi#216]
- [x] 转身速度再缩小-追加修改位置

- [x] 下落加速度调小-追加修改位置

**Comment by IpursueI** [comment]
转身速度修改位置 CustomPhysics/Globals.cs     public const float INPUT_THRESHOLD

下落加速度修改位置CustomPhysics/PlatformerMotor2D.cs  gravityMultiplier, fastFallGravityMultiplier

**Comment by umiringo** [comment]
转身修改速度还有个地方控制了PlayerController中的if (Mathf.Abs(valueCheck) >= 0.1f)

**Comment by umiringo** [comment]
要迅速转身还得调整惯性

**Comment by umiringo** [comment]
跳跃高度根据按键时间控制
